/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/validate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/validate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyBuildManifest,
  BuildManifestFormats
} from ".";
import * as Validators from "../../validators";
import schema_0_0_1_prealpha_1 from "@polywrap/polywrap-manifest-schemas/formats/schemas/polywrap.build/0.0.1-prealpha.1.json";
import schema_0_0_1_prealpha_2 from "@polywrap/polywrap-manifest-schemas/formats/schemas/polywrap.build/0.0.1-prealpha.2.json";
import schema_0_0_1_prealpha_3 from "@polywrap/polywrap-manifest-schemas/formats/schemas/polywrap.build/0.0.1-prealpha.3.json";
import { Tracer } from "@polywrap/tracing-js"

import {
  Schema,
  Validator,
  ValidationError,
  ValidatorResult
} from "jsonschema";

type BuildManifestSchemas = {
  [key in BuildManifestFormats]: Schema | undefined
};

const schemas: BuildManifestSchemas = {
  "0.0.1-prealpha.1": schema_0_0_1_prealpha_1,
  "0.0.1-prealpha.2": schema_0_0_1_prealpha_2,
  "0.0.1-prealpha.3": schema_0_0_1_prealpha_3,
};

const validator = new Validator();

Validator.prototype.customFormats.dockerImageName = Validators.dockerImageName;
Validator.prototype.customFormats.dockerfileName = Validators.dockerfileName;
Validator.prototype.customFormats.dockerImageId = Validators.dockerImageId;
Validator.prototype.customFormats.regexString = Validators.regexString;
Validator.prototype.customFormats.directory = Validators.directory;

export const validateBuildManifest = Tracer.traceFunc(
  "core: validateBuildManifest",
  (
    manifest: AnyBuildManifest,
    extSchema: Schema | undefined = undefined
  ): void => {
    const schema = schemas[manifest.format as BuildManifestFormats];

    if (!schema) {
      throw Error(`Unrecognized BuildManifest schema format "${manifest.format}"\nmanifest: ${JSON.stringify(manifest, null, 2)}`);
    }

    const throwIfErrors = (result: ValidatorResult) => {
      if (result.errors.length) {
        throw new Error([
          `Validation errors encountered while sanitizing BuildManifest format ${manifest.format}`,
          ...result.errors.map((error: ValidationError) => error.toString())
        ].join("\n"));
      }
    };

    throwIfErrors(validator.validate(manifest, schema));

    if (extSchema) {
      throwIfErrors(validator.validate(manifest, extSchema));
    }
  }
);
