/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  MetaManifest as MetaManifest_0_1
} from "./0.1";

export {
  MetaManifest_0_1,
};

export enum MetaManifestFormats {
  "v0.1" = "0.1",
}

export type AnyMetaManifest =
  | MetaManifest_0_1

export type MetaManifest = MetaManifest_0_1;

export const latestMetaManifestFormat = MetaManifestFormats["v0.1"]

export { migrateMetaManifest } from "./migrate";

export { deserializeMetaManifest } from "./deserialize";

export { validateMetaManifest } from "./validate";
