/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  MetaManifest as MetaManifest0_1_0
} from "./0.1.0";

export {
  MetaManifest0_1_0,
};

export enum MetaManifestFormats {
  "0.1.0" = "0.1.0",
}

export type AnyMetaManifest =
  | MetaManifest0_1_0

export type MetaManifest = MetaManifest0_1_0;

export const latestMetaManifestFormat = MetaManifestFormats["0.1.0"]

export { migrateMetaManifest } from "./migrate";

export { deserializeMetaManifest } from "./deserialize";

export { validateMetaManifest } from "./validate";
