/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyMetaManifest,
  MetaManifest,
  MetaManifestFormats,
  latestMetaManifestFormat
} from ".";


type Migrator = {
  [key in MetaManifestFormats]?: (m: AnyMetaManifest) => MetaManifest;
};

export const migrators: Migrator = {
};

export function migrateMetaManifest(
  manifest: AnyMetaManifest,
  to: MetaManifestFormats
): MetaManifest {
  let from = manifest.format as MetaManifestFormats;

  // HACK: Patch fix for backwards compatability
  if(from === "0.1" && ("0.1.0" in migrators)) {
    from = "0.1.0" as MetaManifestFormats;
  }

  if (from === latestMetaManifestFormat) {
    return manifest as MetaManifest;
  }

  if (!(Object.values(MetaManifestFormats).some(x => x === from))) {
    throw new Error(`Unrecognized MetaManifestFormat "${manifest.format}"`);
  }

  throw new Error(`This should never happen, MetaManifest migrators is empty. from: ${from}, to: ${to}`);
}
