/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyMetaManifest,
  MetaManifest,
  MetaManifestFormats,
  latestMetaManifestFormat
} from ".";

import {
  migrate as migrate_0_0_1_prealpha_1_to_0_0_1_prealpha_3
} from "./migrators/0.0.1-prealpha.1_to_0.0.1-prealpha.3";
import {
  migrate as migrate_0_0_1_prealpha_2_to_0_0_1_prealpha_3
} from "./migrators/0.0.1-prealpha.2_to_0.0.1-prealpha.3";

type Migrator = {
  [key in MetaManifestFormats]?: (m: AnyMetaManifest) => MetaManifest;
};

export const migrators: Migrator = {
  "0.0.1-prealpha.1": migrate_0_0_1_prealpha_1_to_0_0_1_prealpha_3,
  "0.0.1-prealpha.2": migrate_0_0_1_prealpha_2_to_0_0_1_prealpha_3,
};

export function migrateMetaManifest(
  manifest: AnyMetaManifest,
  to: MetaManifestFormats
): MetaManifest {
  const from = manifest.format as MetaManifestFormats;

  if (from === latestMetaManifestFormat) {
    return manifest as MetaManifest;
  }

  if (!(from in MetaManifestFormats)) {
    throw new Error(`Unrecognized MetaManifestFormat "${manifest.format}"`);
  }

  const migrator = migrators[from];
  if (!migrator) {
    throw new Error(
      `Migrator from MetaManifestFormat "${from}" to "${to}" is not available`
    );
  }

  return migrator(manifest);
}
