export const wrapManifest = {
  name: "FileSystemResolver",
  type: "plugin",
  version: "0.1",
  abi: {
    objectTypes: [],
    enumTypes: [],
    interfaceTypes: [],
    importedObjectTypes: [
      {
        type: "UriResolver_MaybeUriOrManifest",
        name: null,
        required: null,
        kind: 1025,
        properties: [
          {
            type: "String",
            name: "uri",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "uri", required: null, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "Bytes",
            name: "manifest",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "Bytes", name: "manifest", required: null, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        interfaces: [],
        uri: "ens/uri-resolver.core.polywrap.eth",
        namespace: "UriResolver",
        nativeType: "MaybeUriOrManifest",
      },
    ],
    importedModuleTypes: [
      {
        type: "UriResolver_Module",
        name: null,
        required: null,
        kind: 256,
        methods: [
          {
            type: "Method",
            name: "tryResolveUri",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "authority",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: {
                  type: "String",
                  name: "authority",
                  required: true,
                  kind: 4,
                },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "UriResolver_MaybeUriOrManifest",
              name: "tryResolveUri",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: null,
              object: {
                type: "UriResolver_MaybeUriOrManifest",
                name: "tryResolveUri",
                required: null,
                kind: 8192,
              },
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "getFile",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "Bytes",
              name: "getFile",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: { type: "Bytes", name: "getFile", required: null, kind: 4 },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
        ],
        uri: "ens/uri-resolver.core.polywrap.eth",
        namespace: "UriResolver",
        nativeType: "Module",
        isInterface: false,
      },
      {
        type: "FileSystem_Module",
        name: null,
        required: null,
        kind: 256,
        methods: [
          {
            type: "Method",
            name: "readFile",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "Bytes",
              name: "readFile",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "Bytes",
                name: "readFile",
                required: true,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "readFileAsString",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "FileSystem_Encoding",
                name: "encoding",
                required: null,
                kind: 34,
                array: null,
                map: null,
                scalar: null,
                object: null,
                enum: {
                  type: "FileSystem_Encoding",
                  name: "encoding",
                  required: null,
                  kind: 16384,
                },
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "String",
              name: "readFileAsString",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "String",
                name: "readFileAsString",
                required: true,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "exists",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "Boolean",
              name: "exists",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "Boolean",
                name: "exists",
                required: true,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "writeFile",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "Bytes",
                name: "data",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "Bytes", name: "data", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "Boolean",
              name: "writeFile",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "Boolean",
                name: "writeFile",
                required: null,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "mkdir",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "Boolean",
                name: "recursive",
                required: null,
                kind: 34,
                array: null,
                map: null,
                scalar: {
                  type: "Boolean",
                  name: "recursive",
                  required: null,
                  kind: 4,
                },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "Boolean",
              name: "mkdir",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: { type: "Boolean", name: "mkdir", required: null, kind: 4 },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "rm",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "Boolean",
                name: "recursive",
                required: null,
                kind: 34,
                array: null,
                map: null,
                scalar: {
                  type: "Boolean",
                  name: "recursive",
                  required: null,
                  kind: 4,
                },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "Boolean",
                name: "force",
                required: null,
                kind: 34,
                array: null,
                map: null,
                scalar: {
                  type: "Boolean",
                  name: "force",
                  required: null,
                  kind: 4,
                },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "Boolean",
              name: "rm",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: { type: "Boolean", name: "rm", required: null, kind: 4 },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "rmdir",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "path",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: { type: "String", name: "path", required: true, kind: 4 },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "Boolean",
              name: "rmdir",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: { type: "Boolean", name: "rmdir", required: null, kind: 4 },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
        ],
        uri: "ens/fs.polywrap.eth",
        namespace: "FileSystem",
        nativeType: "Module",
        isInterface: false,
      },
    ],
    importedEnumTypes: [
      {
        type: "FileSystem_Encoding",
        name: null,
        required: null,
        kind: 520,
        constants: [
          "ASCII",
          "UTF8",
          "UTF16LE",
          "UCS2",
          "BASE64",
          "BASE64URL",
          "LATIN1",
          "BINARY",
          "HEX",
        ],
        uri: "ens/fs.polywrap.eth",
        namespace: "FileSystem",
        nativeType: "Encoding",
      },
    ],
    importedEnvTypes: [],
    moduleType: {
      type: "Module",
      name: null,
      required: null,
      kind: 128,
      methods: [
        {
          type: "Method",
          name: "tryResolveUri",
          required: true,
          kind: 64,
          arguments: [
            {
              type: "String",
              name: "authority",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "String",
                name: "authority",
                required: true,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
            {
              type: "String",
              name: "path",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: { type: "String", name: "path", required: true, kind: 4 },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          ],
          return: {
            type: "UriResolver_MaybeUriOrManifest",
            name: "tryResolveUri",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: null,
            object: {
              type: "UriResolver_MaybeUriOrManifest",
              name: "tryResolveUri",
              required: null,
              kind: 8192,
            },
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        },
        {
          type: "Method",
          name: "getFile",
          required: true,
          kind: 64,
          arguments: [
            {
              type: "String",
              name: "path",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: { type: "String", name: "path", required: true, kind: 4 },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          ],
          return: {
            type: "Bytes",
            name: "getFile",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "Bytes", name: "getFile", required: null, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        },
      ],
      imports: [
        { type: "UriResolver_Module" },
        { type: "UriResolver_MaybeUriOrManifest" },
        { type: "FileSystem_Module" },
        { type: "FileSystem_Encoding" },
      ],
      interfaces: [
        {
          type: "UriResolver_Module",
          name: null,
          required: null,
          kind: 2048,
          array: null,
          map: null,
          scalar: null,
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      ],
    }
  }
};
