/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PolywrapManifest {
  format: "0.0.1-prealpha.1";
  /**
   * Description about this wrapper.
   */
  description?: string;
  /**
   * Reference to the repository holding source code.
   */
  repository?: string;
  /**
   * Mutation module metadata.
   */
  mutation?: {
    /**
     * Path to graphql schema.
     */
    schema: {
      /**
       * Path to graphql schema file.
       */
      file: string;
    };
    /**
     * Module for mutation operations.
     */
    module: {
      /**
       * Language in which the source code is written.
       */
      language: string;
      /**
       * Path to Polywrap module implementation file.
       */
      file: string;
    };
  };
  /**
   * Module for query operations.
   */
  query?: {
    /**
     * Path to graphql schema.
     */
    schema: {
      /**
       * Path to graphql schema file.
       */
      file: string;
    };
    /**
     * Module for query operations.
     */
    module: {
      /**
       * Language in which the source code is written.
       */
      language: string;
      /**
       * Path to Polywrap module implementation file.
       */
      file: string;
    };
  };
  /**
   * Redirects enabling the import of plugins.
   */
  import_redirects?: {
    /**
     * URI resolving to the plugin schema.
     */
    uri: string;
    /**
     * Graphql schema for imported plugin.
     */
    schema: string;
  }[];
  __type: "PolywrapManifest";
}
