/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/deserialize-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/deserialize-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  PolywrapManifest,
  AnyPolywrapManifest,
  migratePolywrapManifest,
  validatePolywrapManifest,
  latestPolywrapManifestFormat,
} from ".";
import { DeserializeManifestOptions } from "../../";

import { compare } from "semver";
import YAML from "js-yaml";
import { Tracer } from "@polywrap/tracing-js";

export const deserializePolywrapManifest = Tracer.traceFunc(
  "core: deserializePolywrapManifest",
  (manifest: string, options?: DeserializeManifestOptions): PolywrapManifest => {
    let anyPolywrapManifest: AnyPolywrapManifest | undefined;
    try {
      anyPolywrapManifest = JSON.parse(manifest) as AnyPolywrapManifest;
    } catch (e) {
      anyPolywrapManifest = YAML.safeLoad(manifest) as
      | AnyPolywrapManifest
      | undefined;
    }

    if (!anyPolywrapManifest) {
      throw Error(`Unable to parse PolywrapManifest: ${manifest}`);
    }

    if (!options || !options.noValidate) {
      validatePolywrapManifest(anyPolywrapManifest, options?.extSchema);
    }

    anyPolywrapManifest.__type = "PolywrapManifest";

    const versionCompare = compare(
      anyPolywrapManifest.format,
      latestPolywrapManifestFormat
    );

    if (versionCompare === -1) {
      // Upgrade
      return migratePolywrapManifest(anyPolywrapManifest, latestPolywrapManifestFormat);
    } else if (versionCompare === 1) {
      // Downgrade
      throw Error(
        `Cannot downgrade Polywrap version ${anyPolywrapManifest.format}, please upgrade your PolywrapClient package.`
      );
    } else {
      // Latest
      return anyPolywrapManifest as PolywrapManifest;
    }
  }
);
