// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

// @ts-noCheck
import {
  UInt,
  UInt8,
  UInt16,
  UInt32,
  Int,
  Int8,
  Int16,
  Int32,
  Bytes,
  BigInt,
  Json,
  String,
  Boolean
} from "../baseTypes";
import * as Types from "./";

export interface Header {
  key: String;
  value: String;
}

export interface UrlParam {
  key: String;
  value: String;
}

export interface Response {
  status: Int;
  statusText: String;
  headers?: Array<Types.Header> | null;
  body?: String | null;
}

export interface Request {
  headers?: Array<Types.Header> | null;
  urlParams?: Array<Types.UrlParam> | null;
  responseType: Types.ResponseType;
  body?: String | null;
}

export enum ResponseTypeEnum {
  TEXT,
  BINARY,
}

export type ResponseTypeString =
  | "TEXT"
  | "BINARY"

export type ResponseType = ResponseTypeEnum | ResponseTypeString;

