export const abi = {
  objectTypes: [],
  enumTypes: [
    {
      type: "LogLevel",
      name: null,
      required: null,
      kind: 8,
      constants: ["DEBUG", "INFO", "WARN", "ERROR"],
    },
  ],
  interfaceTypes: [],
  importedObjectTypes: [],
  importedModuleTypes: [],
  importedEnumTypes: [],
  importedEnvTypes: [],
  moduleType: {
    type: "Module",
    name: null,
    required: null,
    kind: 128,
    methods: [
      {
        type: "Method",
        name: "log",
        required: true,
        kind: 64,
        arguments: [
          {
            type: "LogLevel",
            name: "level",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: null,
            object: null,
            enum: {
              type: "LogLevel",
              name: "level",
              required: true,
              kind: 16384,
            },
            unresolvedObjectOrEnum: null,
          },
          {
            type: "String",
            name: "message",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: {
              type: "String",
              name: "message",
              required: true,
              kind: 4,
            },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        return: {
          type: "Boolean",
          name: "log",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "Boolean", name: "log", required: true, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      },
    ],
    imports: [],
    interfaces: [],
  },
};
