/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  PluginManifest as PluginManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";

export {
  PluginManifest0_0_1_prealpha_1,
};

export enum PluginManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
}

export type AnyPluginManifest =
  | PluginManifest0_0_1_prealpha_1

export type PluginManifest = PluginManifest0_0_1_prealpha_1;

export const latestPluginManifestFormat = PluginManifestFormats["0.0.1-prealpha.1"]

export { migratePluginManifest } from "./migrate";

export { deserializePluginManifest } from "./deserialize";

export { validatePluginManifest } from "./validate";
