/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  AppManifest as AppManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";

export {
  AppManifest0_0_1_prealpha_1,
};

export enum AppManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
}

export type AnyAppManifest =
  | AppManifest0_0_1_prealpha_1

export type AppManifest = AppManifest0_0_1_prealpha_1;

export const latestAppManifestFormat = AppManifestFormats["0.0.1-prealpha.1"]

export { migrateAppManifest } from "./migrate";

export { deserializeAppManifest } from "./deserialize";

export { validateAppManifest } from "./validate";
