/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyAppManifest,
  AppManifest,
  AppManifestFormats,
  latestAppManifestFormat
} from ".";


import { Tracer } from "@web3api/tracing-js";

type Migrator = {
  [key in AppManifestFormats]?: (m: AnyAppManifest) => AppManifest;
};

export const migrators: Migrator = {
};

export const migrateAppManifest = Tracer.traceFunc(
  "core: migrateAppManifest",
  (manifest: AnyAppManifest, to: AppManifestFormats): AppManifest => {
    const from = manifest.format as AppManifestFormats;

    if (from === latestAppManifestFormat) {
      return manifest as AppManifest;
    }

    if (!(from in AppManifestFormats)) {
      throw new Error(`Unrecognized AppManifestFormat "${manifest.format}"`);
    }

    throw new Error(`This should never happen, AppManifest migrators is empty. from: ${from}, to: ${to}`);
  }
);
