/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyAppManifest,
  AppManifest,
  AppManifestFormats,
  latestAppManifestFormat
} from ".";

import {
  migrate as migrate_0_0_1_prealpha_1_to_0_0_1_prealpha_2
} from "./migrators/0.0.1-prealpha.1_to_0.0.1-prealpha.2";

import { Tracer } from "@polywrap/tracing-js";

type Migrator = {
  [key in AppManifestFormats]?: (m: AnyAppManifest) => AppManifest;
};

export const migrators: Migrator = {
  "0.0.1-prealpha.1": migrate_0_0_1_prealpha_1_to_0_0_1_prealpha_2,
};

export const migrateAppManifest = Tracer.traceFunc(
  "core: migrateAppManifest",
  (manifest: AnyAppManifest, to: AppManifestFormats): AppManifest => {
    const from = manifest.format as AppManifestFormats;

    if (from === latestAppManifestFormat) {
      return manifest as AppManifest;
    }

    if (!(from in AppManifestFormats)) {
      throw new Error(`Unrecognized AppManifestFormat "${manifest.format}"`);
    }

    const migrator = migrators[from];
    if (!migrator) {
      throw new Error(
        `Migrator from AppManifestFormat "${from}" to "${to}" is not available`
      );
    }

    return migrator(manifest);
  }
);
