/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  BuildManifest as BuildManifest_0_1
} from "./0.1";

export {
  BuildManifest_0_1,
};

export enum BuildManifestFormats {
  "v0.1" = "0.1",
}

export type AnyBuildManifest =
  | BuildManifest_0_1

export type BuildManifest = BuildManifest_0_1;

export const latestBuildManifestFormat = BuildManifestFormats["v0.1"]

export { migrateBuildManifest } from "./migrate";

export { deserializeBuildManifest } from "./deserialize";

export { validateBuildManifest } from "./validate";
