/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyBuildManifest,
  BuildManifest,
  BuildManifestFormats,
  latestBuildManifestFormat
} from ".";


type Migrator = {
  [key in BuildManifestFormats]?: (m: AnyBuildManifest) => BuildManifest;
};

export const migrators: Migrator = {
};

export function migrateBuildManifest(
  manifest: AnyBuildManifest,
  to: BuildManifestFormats
): BuildManifest {
  const from = manifest.format as BuildManifestFormats;

  if (from === latestBuildManifestFormat) {
    return manifest as BuildManifest;
  }

  if (!(from in BuildManifestFormats)) {
    throw new Error(`Unrecognized BuildManifestFormat "${manifest.format}"`);
  }

  throw new Error(`This should never happen, BuildManifest migrators is empty. from: ${from}, to: ${to}`);
}
