/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeployManifest {
  /**
   * Polywrap deployment manifest format version.
   */
  format: "0.0.1-prealpha.1";
  stages: {
    /**
     * Deployment stage.
     *
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: {
      /**
       * Name of the publisher plugin.
       */
      package: string;
      /**
       * Custom configuration.
       */
      config?: {
        [k: string]: unknown;
      };
      /**
       * Name of the required stage.
       */
      depends_on?: string;
      /**
       * URI resolving to the publisher plugin.
       */
      uri?: string;
    };
  };
  __type: "DeployManifest";
}
