import { WrapManifest } from "@polywrap/wrap-manifest-types-js";

export const manifest: WrapManifest = {
  name: "GraphNode",
  type: "plugin",
  version: "0.1",
  abi: {
    objectTypes: [],
    enumTypes: [],
    interfaceTypes: [],
    importedObjectTypes: [
      {
        type: "HTTP_Request",
        name: null,
        required: null,
        kind: 1025,
        properties: [
          {
            type: "[HTTP_Header]",
            name: "headers",
            required: null,
            kind: 34,
            array: {
              type: "[HTTP_Header]",
              name: "headers",
              required: null,
              kind: 18,
              array: null,
              map: null,
              scalar: null,
              object: {
                type: "HTTP_Header",
                name: "headers",
                required: true,
                kind: 8192,
              },
              enum: null,
              unresolvedObjectOrEnum: null,
              item: {
                type: "HTTP_Header",
                name: "headers",
                required: true,
                kind: 8192,
              },
            },
            map: null,
            scalar: null,
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "[HTTP_UrlParam]",
            name: "urlParams",
            required: null,
            kind: 34,
            array: {
              type: "[HTTP_UrlParam]",
              name: "urlParams",
              required: null,
              kind: 18,
              array: null,
              map: null,
              scalar: null,
              object: {
                type: "HTTP_UrlParam",
                name: "urlParams",
                required: true,
                kind: 8192,
              },
              enum: null,
              unresolvedObjectOrEnum: null,
              item: {
                type: "HTTP_UrlParam",
                name: "urlParams",
                required: true,
                kind: 8192,
              },
            },
            map: null,
            scalar: null,
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "HTTP_ResponseType",
            name: "responseType",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: null,
            object: null,
            enum: {
              type: "HTTP_ResponseType",
              name: "responseType",
              required: true,
              kind: 16384,
            },
            unresolvedObjectOrEnum: null,
          },
          {
            type: "String",
            name: "body",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "body", required: null, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        interfaces: [],
        uri: "ens/http.polywrap.eth",
        namespace: "HTTP",
        nativeType: "Request",
      },
      {
        type: "HTTP_Header",
        name: null,
        required: null,
        kind: 1025,
        properties: [
          {
            type: "String",
            name: "key",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "key", required: true, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "String",
            name: "value",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "value", required: true, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        interfaces: [],
        uri: "ens/http.polywrap.eth",
        namespace: "HTTP",
        nativeType: "Header",
      },
      {
        type: "HTTP_UrlParam",
        name: null,
        required: null,
        kind: 1025,
        properties: [
          {
            type: "String",
            name: "key",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "key", required: true, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "String",
            name: "value",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "value", required: true, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        interfaces: [],
        uri: "ens/http.polywrap.eth",
        namespace: "HTTP",
        nativeType: "UrlParam",
      },
      {
        type: "HTTP_Response",
        name: null,
        required: null,
        kind: 1025,
        properties: [
          {
            type: "Int",
            name: "status",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "Int", name: "status", required: true, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "String",
            name: "statusText",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: {
              type: "String",
              name: "statusText",
              required: true,
              kind: 4,
            },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "[HTTP_Header]",
            name: "headers",
            required: null,
            kind: 34,
            array: {
              type: "[HTTP_Header]",
              name: "headers",
              required: null,
              kind: 18,
              array: null,
              map: null,
              scalar: null,
              object: {
                type: "HTTP_Header",
                name: "headers",
                required: true,
                kind: 8192,
              },
              enum: null,
              unresolvedObjectOrEnum: null,
              item: {
                type: "HTTP_Header",
                name: "headers",
                required: true,
                kind: 8192,
              },
            },
            map: null,
            scalar: null,
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "String",
            name: "body",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "body", required: null, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        interfaces: [],
        uri: "ens/http.polywrap.eth",
        namespace: "HTTP",
        nativeType: "Response",
      },
    ],
    importedModuleTypes: [
      {
        type: "HTTP_Module",
        name: null,
        required: null,
        kind: 256,
        methods: [
          {
            type: "Method",
            name: "get",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "url",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: {
                  type: "String",
                  name: "url",
                  required: true,
                  kind: 4,
                },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "HTTP_Request",
                name: "request",
                required: null,
                kind: 34,
                array: null,
                map: null,
                scalar: null,
                object: {
                  type: "HTTP_Request",
                  name: "request",
                  required: null,
                  kind: 8192,
                },
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "HTTP_Response",
              name: "get",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: null,
              object: {
                type: "HTTP_Response",
                name: "get",
                required: null,
                kind: 8192,
              },
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
          {
            type: "Method",
            name: "post",
            required: true,
            kind: 64,
            arguments: [
              {
                type: "String",
                name: "url",
                required: true,
                kind: 34,
                array: null,
                map: null,
                scalar: {
                  type: "String",
                  name: "url",
                  required: true,
                  kind: 4,
                },
                object: null,
                enum: null,
                unresolvedObjectOrEnum: null,
              },
              {
                type: "HTTP_Request",
                name: "request",
                required: null,
                kind: 34,
                array: null,
                map: null,
                scalar: null,
                object: {
                  type: "HTTP_Request",
                  name: "request",
                  required: null,
                  kind: 8192,
                },
                enum: null,
                unresolvedObjectOrEnum: null,
              },
            ],
            return: {
              type: "HTTP_Response",
              name: "post",
              required: null,
              kind: 34,
              array: null,
              map: null,
              scalar: null,
              object: {
                type: "HTTP_Response",
                name: "post",
                required: null,
                kind: 8192,
              },
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          },
        ],
        uri: "ens/http.polywrap.eth",
        namespace: "HTTP",
        nativeType: "Module",
        isInterface: false,
      },
    ],
    importedEnumTypes: [
      {
        type: "HTTP_ResponseType",
        name: null,
        required: null,
        kind: 520,
        constants: ["TEXT", "BINARY"],
        uri: "ens/http.polywrap.eth",
        namespace: "HTTP",
        nativeType: "ResponseType",
      },
    ],
    importedEnvTypes: [],
    moduleType: {
      type: "Module",
      name: null,
      required: null,
      kind: 128,
      methods: [
        {
          type: "Method",
          name: "querySubgraph",
          required: true,
          kind: 64,
          arguments: [
            {
              type: "String",
              name: "subgraphAuthor",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "String",
                name: "subgraphAuthor",
                required: true,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
            {
              type: "String",
              name: "subgraphName",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "String",
                name: "subgraphName",
                required: true,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
            {
              type: "String",
              name: "query",
              required: true,
              kind: 34,
              array: null,
              map: null,
              scalar: {
                type: "String",
                name: "query",
                required: true,
                kind: 4,
              },
              object: null,
              enum: null,
              unresolvedObjectOrEnum: null,
            },
          ],
          return: {
            type: "String",
            name: "querySubgraph",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: {
              type: "String",
              name: "querySubgraph",
              required: true,
              kind: 4,
            },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        },
      ],
      imports: [
        { type: "HTTP_Module" },
        { type: "HTTP_Request" },
        { type: "HTTP_Header" },
        { type: "HTTP_UrlParam" },
        { type: "HTTP_ResponseType" },
        { type: "HTTP_Response" },
      ],
      interfaces: [],
    },
  },
};
