"""
This type stub file was generated by pyright.
"""

@9
class :
     ...


@9
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@<Expression>
@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@<Expression>
@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@<Expression>
class :
     ...


@<Expression>
@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
@9
class :
     ...


@<Expression>
@<Expression>
class :
     ...


@9
class :
     ...


@9(<Expression>)
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


Usage: <Expression>
packer = ...
Arguments: <Expression>
object: <Expression>
unpacker = ...
unpacker = ...
autoreset = ...
See: <Expression>
