/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AppManifest {
  /**
   * Polywrap app manifest format version.
   */
  format: "0.0.1-prealpha.2";
  /**
   * Name of this wrapper package.
   */
  name: string;
  /**
   * Language in which the source code is written.
   */
  language: string;
  /**
   * Path to graphql schema.
   */
  schema: string;
  /**
   * Redirects enabling the import of plugins.
   */
  import_redirects?: {
    /**
     * URI resolving to the plugin schema.
     */
    uri: string;
    /**
     * Graphql schema for imported plugin.
     */
    schema: string;
  }[];
  __type: "AppManifest";
}
