/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  AppManifest as AppManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";
import {
  AppManifest as AppManifest0_0_1_prealpha_2
} from "./0.0.1-prealpha.2";

export {
  AppManifest0_0_1_prealpha_1,
  AppManifest0_0_1_prealpha_2,
};

export enum AppManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
  "0.0.1-prealpha.2" = "0.0.1-prealpha.2",
}

export type AnyAppManifest =
  | AppManifest0_0_1_prealpha_1
  | AppManifest0_0_1_prealpha_2

export type AppManifest = AppManifest0_0_1_prealpha_2;

export const latestAppManifestFormat = AppManifestFormats["0.0.1-prealpha.2"]

export { migrateAppManifest } from "./migrate";

export { deserializeAppManifest } from "./deserialize";

export { validateAppManifest } from "./validate";
