/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WrapManifest {
  /**
   * WRAP Standard Version
   */
  version: "0.1.0";
  /**
   * Wrapper Package Type
   */
  type: "wasm" | "interface" | "plugin";
  /**
   * Wrapper Name
   */
  name: string;
  /**
   * Wrapper ABI
   */
  abi: {
    [k: string]: unknown;
  };
}
