/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateTypes.js to regenerate this file.
 */

import {
  WrapManifest as WrapManifest_0_1,
  Abi as WrapAbi_0_1_0_1
} from "./0.1";

import schema_0_1 from "./0.1.schema.json";

export {
  WrapManifest_0_1,
  WrapAbi_0_1_0_1,
  schema_0_1
};

export enum WrapManifestVersions {
  // NOTE: Patch fix for backwards compatability
  "v0.1.0" = "0.1.0",
  "v0.1" = "0.1",
};

export enum WrapManifestAbiVersions {
  "v0.1" = "0.1",
};

export enum WrapAbiVersions {
  "v0.1" = "0.1",
};

export type AnyWrapManifest =
  | WrapManifest_0_1
;

export type AnyWrapAbi =
  | WrapAbi_0_1_0_1
;

export type WrapManifest = WrapManifest_0_1;
export type WrapAbi = WrapAbi_0_1_0_1;

export const latestWrapManifestVersion = WrapManifestVersions["v0.1"];
export const latestWrapAbiVersion = "0.1";

export { migrateWrapManifest } from "./migrate";
export { deserializeWrapManifest } from "./deserialize";
export { validateWrapManifest } from "./validate";
