/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateTypes.js to regenerate this file.
 */

import {
  WrapManifest as WrapManifest0_1_0,
  Abi as WrapAbi0_1_0
} from "./0.1.0";

export {
  WrapManifest0_1_0,
  WrapAbi0_1_0,
};

export enum WrapManifestVersions {
  "0.1.0" = "0.1.0",
}

export type AnyWrapManifest =
  | WrapManifest0_1_0
export type AnyWrapAbi =
  | WrapAbi0_1_0

export type WrapManifest = WrapManifest0_1_0;
export type WrapAbi = WrapAbi0_1_0;

export const latestWrapManifestVersion = WrapManifestVersions["0.1.0"]

export { migrateWrapManifest } from "./migrate";

export { deserializeWrapManifest } from "./deserialize";

export { validateWrapManifest } from "./validate";
