/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyWrapManifest,
  WrapManifest,
  WrapManifestVersions,
  latestWrapManifestVersion
} from ".";


type Migrator = {
  [key in WrapManifestVersions]?: (m: AnyWrapManifest) => WrapManifest;
};

export const migrators: Migrator = {
};

export function migrateWrapManifest(
  manifest: AnyWrapManifest,
  to: WrapManifestVersions
): WrapManifest {
  const from = manifest.version as WrapManifestVersions;

  if (from === latestWrapManifestVersion) {
    return manifest as WrapManifest;
  }

  if (!(from in WrapManifestVersions)) {
    throw new Error(`Unrecognized WrapManifestVersion "${manifest.version}"`);
  }

  throw new Error(`This should never happen, WrapManifest migrators is empty. from: ${from}, to: ${to}`);
}
