/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/deserialize-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/deserialize-ts.mustache,
 * and run node ./scripts/manifest/generateTypes.js to regenerate this file.
 */

import {
  WrapManifest,
  AnyWrapManifest,
  migrateWrapManifest,
  validateWrapManifest,
  latestWrapManifestVersion,
} from ".";
import { msgpackDecode } from "../../";

import { compare } from "semver";
import { Tracer } from "@polywrap/tracing-js";

export interface DeserializeWrapManifestOptions {
  noValidate?: boolean;
}

export const deserializeWrapManifest = Tracer.traceFunc(
  "core: deserializeWrapManifest",
  (manifest: ArrayBufferView, options?: DeserializeWrapManifestOptions): WrapManifest => {
    let anyWrapManifest: AnyWrapManifest | undefined;
    try {
      anyWrapManifest = msgpackDecode(manifest) as AnyWrapManifest;
    } catch (e) {
      throw Error(
        `Unable to parse WrapManifest: ` +
        `[${new Uint8Array(manifest.buffer, manifest.byteOffset, manifest.byteLength).toString()}]`
      );
    }

    if (!options || !options.noValidate) {
      validateWrapManifest(anyWrapManifest);
    }

    const versionCompare = compare(
      anyWrapManifest.version,
      latestWrapManifestVersion
    );

    if (versionCompare === -1) {
      // Upgrade
      return migrateWrapManifest(anyWrapManifest, latestWrapManifestVersion);
    } else if (versionCompare === 1) {
      // Downgrade
      throw Error(
        `Cannot downgrade WrapManifest version ${anyWrapManifest.version}, please upgrade your WRAP package.`
      );
    } else {
      // Latest
      return anyWrapManifest as WrapManifest;
    }
  }
);
