/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  InfraManifest as InfraManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";
import {
  InfraManifest as InfraManifest0_0_1_prealpha_2
} from "./0.0.1-prealpha.2";

export {
  InfraManifest0_0_1_prealpha_1,
  InfraManifest0_0_1_prealpha_2,
};

export enum InfraManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
  "0.0.1-prealpha.2" = "0.0.1-prealpha.2",
}

export type AnyInfraManifest =
  | InfraManifest0_0_1_prealpha_1
  | InfraManifest0_0_1_prealpha_2

export type InfraManifest = InfraManifest0_0_1_prealpha_2;

export const latestInfraManifestFormat = InfraManifestFormats["0.0.1-prealpha.2"]

export { migrateInfraManifest } from "./migrate";

export { deserializeInfraManifest } from "./deserialize";

export { validateInfraManifest } from "./validate";
