/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Web3ApiManifest {
  format: "0.0.1-prealpha.9";
  name: string;
  build?: string;
  meta?: string;
  deploy?: string;
  language: string;
  module?: string;
  schema: string;
  import_redirects?: {
    uri: string;
    schema: string;
  }[];
  __type: "Web3ApiManifest";
}
