/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeployManifest {
  /**
   * Polywrap deployment manifest format version.
   */
  format: "0.2";
  /**
   * Sequences of deployment steps
   */
  sequences: {
    /**
     * Name of the sequence
     */
    name: string;
    /**
     * Deployment steps
     */
    steps: {
      /**
       * Name of the step
       */
      name: string;
      /**
       * Name of the deployer package.
       */
      package: string;
      /**
       * Step-level custom configuration.
       */
      config?: {
        [k: string]: unknown;
      };
      /**
       * URI to pass into the deploy step.
       */
      uri: string | string;
    }[];
    /**
     * Sequence-level custom configuration.
     */
    config?: {
      [k: string]: unknown;
    };
  }[];
  __type: "DeployManifest";
}
