/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  BuildManifest as BuildManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";
import {
  BuildManifest as BuildManifest0_0_1_prealpha_2
} from "./0.0.1-prealpha.2";
import {
  BuildManifest as BuildManifest0_0_1_prealpha_3
} from "./0.0.1-prealpha.3";

export {
  BuildManifest0_0_1_prealpha_1,
  BuildManifest0_0_1_prealpha_2,
  BuildManifest0_0_1_prealpha_3,
};

export enum BuildManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
  "0.0.1-prealpha.2" = "0.0.1-prealpha.2",
  "0.0.1-prealpha.3" = "0.0.1-prealpha.3",
}

export type AnyBuildManifest =
  | BuildManifest0_0_1_prealpha_1
  | BuildManifest0_0_1_prealpha_2
  | BuildManifest0_0_1_prealpha_3

export type BuildManifest = BuildManifest0_0_1_prealpha_3;

export const latestBuildManifestFormat = BuildManifestFormats["0.0.1-prealpha.3"]

export { migrateBuildManifest } from "./migrate";

export { deserializeBuildManifest } from "./deserialize";

export { validateBuildManifest } from "./validate";
