/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InfraManifest {
  /**
   * Polywrap infra manifest format version.
   */
  format: "0.0.1-prealpha.1";
  /**
   * Path to docker compose manifest.
   */
  dockerCompose?: string;
  env?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: string | number;
  };
  modules: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: RemoteModule | LocalModule;
  };
  __type: "InfraManifest";
}
/**
 * A remote docker-compose package.
 */
export interface RemoteModule {
  /**
   * Package name.
   */
  package: string;
  /**
   * Package registry name.
   */
  registry: string;
  /**
   * Package version.
   */
  version: string;
  /**
   * Path to docker-compose file in the package directory.
   */
  dockerComposePath?: string;
}
export interface LocalModule {
  /**
   * Path to the package.
   */
  path: string;
}
