/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeployManifest {
  format: "0.0.1-prealpha.1";
  deployments: {
    name: string;
    deploy?: {
      package: {
        name: string;
        versionOrPath: string;
      };
      config?: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^.*$".
         */
        [k: string]: string | number;
      };
    };
    publish?: {
      package: {
        name: string;
        versionOrPath: string;
      };
      config?: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^.*$".
         */
        [k: string]: string | number;
      };
    };
  }[];
  __type: "DeployManifest";
}
