export const abi = {
  objectTypes: [
    {
      type: "Header",
      name: null,
      required: null,
      kind: 1,
      properties: [
        {
          type: "String",
          name: "key",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "String", name: "key", required: true, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
        {
          type: "String",
          name: "value",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "String", name: "value", required: true, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      ],
      interfaces: [],
    },
    {
      type: "UrlParam",
      name: null,
      required: null,
      kind: 1,
      properties: [
        {
          type: "String",
          name: "key",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "String", name: "key", required: true, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
        {
          type: "String",
          name: "value",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "String", name: "value", required: true, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      ],
      interfaces: [],
    },
    {
      type: "Response",
      name: null,
      required: null,
      kind: 1,
      properties: [
        {
          type: "Int",
          name: "status",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "Int", name: "status", required: true, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
        {
          type: "String",
          name: "statusText",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: {
            type: "String",
            name: "statusText",
            required: true,
            kind: 4,
          },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
        {
          type: "[Header]",
          name: "headers",
          required: null,
          kind: 34,
          array: {
            type: "[Header]",
            name: "headers",
            required: null,
            kind: 18,
            array: null,
            map: null,
            scalar: null,
            object: {
              type: "Header",
              name: "headers",
              required: true,
              kind: 8192,
            },
            enum: null,
            unresolvedObjectOrEnum: null,
            item: {
              type: "Header",
              name: "headers",
              required: true,
              kind: 8192,
            },
          },
          map: null,
          scalar: null,
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
        {
          type: "String",
          name: "body",
          required: null,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "String", name: "body", required: null, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      ],
      interfaces: [],
    },
    {
      type: "Request",
      name: null,
      required: null,
      kind: 1,
      properties: [
        {
          type: "[Header]",
          name: "headers",
          required: null,
          kind: 34,
          array: {
            type: "[Header]",
            name: "headers",
            required: null,
            kind: 18,
            array: null,
            map: null,
            scalar: null,
            object: {
              type: "Header",
              name: "headers",
              required: true,
              kind: 8192,
            },
            enum: null,
            unresolvedObjectOrEnum: null,
            item: {
              type: "Header",
              name: "headers",
              required: true,
              kind: 8192,
            },
          },
          map: null,
          scalar: null,
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
        {
          type: "[UrlParam]",
          name: "urlParams",
          required: null,
          kind: 34,
          array: {
            type: "[UrlParam]",
            name: "urlParams",
            required: null,
            kind: 18,
            array: null,
            map: null,
            scalar: null,
            object: {
              type: "UrlParam",
              name: "urlParams",
              required: true,
              kind: 8192,
            },
            enum: null,
            unresolvedObjectOrEnum: null,
            item: {
              type: "UrlParam",
              name: "urlParams",
              required: true,
              kind: 8192,
            },
          },
          map: null,
          scalar: null,
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
        {
          type: "ResponseType",
          name: "responseType",
          required: true,
          kind: 34,
          array: null,
          map: null,
          scalar: null,
          object: null,
          enum: {
            type: "ResponseType",
            name: "responseType",
            required: true,
            kind: 16384,
          },
          unresolvedObjectOrEnum: null,
        },
        {
          type: "String",
          name: "body",
          required: null,
          kind: 34,
          array: null,
          map: null,
          scalar: { type: "String", name: "body", required: null, kind: 4 },
          object: null,
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      ],
      interfaces: [],
    },
  ],
  enumTypes: [
    {
      type: "ResponseType",
      name: null,
      required: null,
      kind: 8,
      constants: ["TEXT", "BINARY"],
    },
  ],
  interfaceTypes: [],
  importedObjectTypes: [],
  importedModuleTypes: [],
  importedEnumTypes: [],
  importedEnvTypes: [],
  moduleType: {
    type: "Module",
    name: null,
    required: null,
    kind: 128,
    methods: [
      {
        type: "Method",
        name: "get",
        required: true,
        kind: 64,
        arguments: [
          {
            type: "String",
            name: "url",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "url", required: true, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "Request",
            name: "request",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: null,
            object: {
              type: "Request",
              name: "request",
              required: null,
              kind: 8192,
            },
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        return: {
          type: "Response",
          name: "get",
          required: null,
          kind: 34,
          array: null,
          map: null,
          scalar: null,
          object: { type: "Response", name: "get", required: null, kind: 8192 },
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      },
      {
        type: "Method",
        name: "post",
        required: true,
        kind: 64,
        arguments: [
          {
            type: "String",
            name: "url",
            required: true,
            kind: 34,
            array: null,
            map: null,
            scalar: { type: "String", name: "url", required: true, kind: 4 },
            object: null,
            enum: null,
            unresolvedObjectOrEnum: null,
          },
          {
            type: "Request",
            name: "request",
            required: null,
            kind: 34,
            array: null,
            map: null,
            scalar: null,
            object: {
              type: "Request",
              name: "request",
              required: null,
              kind: 8192,
            },
            enum: null,
            unresolvedObjectOrEnum: null,
          },
        ],
        return: {
          type: "Response",
          name: "post",
          required: null,
          kind: 34,
          array: null,
          map: null,
          scalar: null,
          object: {
            type: "Response",
            name: "post",
            required: null,
            kind: 8192,
          },
          enum: null,
          unresolvedObjectOrEnum: null,
        },
      },
    ],
    imports: [],
    interfaces: [],
  },
};
