/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EnvManifest {
  format: "0.0.1-prealpha.2";
  dockerCompose?: unknown;
  env?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: string | number;
  };
  modules?: {
    name: string;
    dockerComposePath?: string;
    module: string;
    version: string;
  }[];
  __type: "EnvManifest";
}
