/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  EnvManifest as EnvManifest0_0_1_prealpha_2
} from "./0.0.1-prealpha.2";

export {
  EnvManifest0_0_1_prealpha_2,
};

export enum EnvManifestFormats {
  "0.0.1-prealpha.2" = "0.0.1-prealpha.2",
}

export type AnyEnvManifest =
  | EnvManifest0_0_1_prealpha_2

export type EnvManifest = EnvManifest0_0_1_prealpha_2;

export const latestEnvManifestFormat = EnvManifestFormats["0.0.1-prealpha.2"]

export { migrateEnvManifest } from "./migrate";

export { deserializeEnvManifest } from "./deserialize";

export { validateEnvManifest } from "./validate";
