/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  EnvManifest as EnvManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";

export {
  EnvManifest0_0_1_prealpha_1,
};

export enum EnvManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
}

export type AnyEnvManifest =
  | EnvManifest0_0_1_prealpha_1

export type EnvManifest = EnvManifest0_0_1_prealpha_1;

export const latestEnvManifestFormat = EnvManifestFormats["0.0.1-prealpha.1"]

export { migrateEnvManifest } from "./migrate";

export { deserializeEnvManifest } from "./deserialize";

export { validateEnvManifest } from "./validate";
