/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyEnvManifest,
  EnvManifest,
  EnvManifestFormats,
  latestEnvManifestFormat
} from ".";


import { Tracer } from "@web3api/tracing-js";

type Migrator = {
  [key in EnvManifestFormats]?: (m: AnyEnvManifest) => EnvManifest;
};

export const migrators: Migrator = {
};

export const migrateEnvManifest = Tracer.traceFunc(
  "core: migrateEnvManifest",
  (manifest: AnyEnvManifest, to: EnvManifestFormats): EnvManifest => {
    const from = manifest.format as EnvManifestFormats;

    if (from === latestEnvManifestFormat) {
      return manifest as EnvManifest;
    }

    if (!(from in EnvManifestFormats)) {
      throw new Error(`Unrecognized EnvManifestFormat "${manifest.format}"`);
    }

    throw new Error(`This should never happen, EnvManifest migrators is empty. from: ${from}, to: ${to}`);
  }
);
