/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/validate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/validate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyEnvManifest,
  EnvManifestFormats
} from ".";

import schema_0_0_1_prealpha_1 from "@web3api/manifest-schemas/formats/web3api.env/0.0.1-prealpha.1.json";
import { Tracer } from "@web3api/tracing-js"

import {
  Schema,
  Validator,
  ValidationError,
  ValidatorResult
} from "jsonschema";

type EnvManifestSchemas = {
  [key in EnvManifestFormats]: Schema | undefined
};

const schemas: EnvManifestSchemas = {
  "0.0.1-prealpha.1": schema_0_0_1_prealpha_1,
};

const validator = new Validator();


export const validateEnvManifest = Tracer.traceFunc(
  "core: validateEnvManifest",
  (
    manifest: AnyEnvManifest,
    extSchema: Schema | undefined = undefined
  ): void => {
    const schema = schemas[manifest.format as EnvManifestFormats];

    if (!schema) {
      throw Error(`Unrecognized EnvManifest schema format "${manifest.format}"`);
    }

    const throwIfErrors = (result: ValidatorResult) => {
      if (result.errors.length) {
        throw new Error([
          `Validation errors encountered while sanitizing EnvManifest format ${manifest.format}`,
          ...result.errors.map((error: ValidationError) => error.toString())
        ].join("\n"));
      }
    };

    throwIfErrors(validator.validate(manifest, schema));

    if (extSchema) {
      throwIfErrors(validator.validate(manifest, extSchema));
    }
  }
);
