# generated by datamodel-codegen:
#   filename:  0.1.0.json
#   timestamp: 2022-09-21T13:12:40+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Extra, Field, constr


class Format(Enum):
    field_0_1_0 = '0.1.0'
    field_0_1 = '0.1'


class Stages(BaseModel):
    class Config:
        extra = Extra.forbid

    package: str = Field(..., description='Name of the deploy stage.')
    config: Optional[Dict[str, Any]] = Field(None, description='Custom configuration.')
    depends_on: Optional[str] = Field(None, description='Name of dependent stages.')
    uri: Optional[constr(regex=r'^[wrap://]*[a-z\\-\\_0-9]+\\/.+$')] = Field(
        None, description='URI to pass into the deploy stage.'
    )


class Model(BaseModel):
    class Config:
        extra = Extra.forbid

    format: Format = Field(
        ..., description='Polywrap deployment manifest format version.'
    )
    stages: Dict[constr(regex=r'^.*$'), Stages]
