/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/deserialize-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/deserialize-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  PolywrapWorkflow,
  AnyPolywrapWorkflow,
  migratePolywrapWorkflow,
  validatePolywrapWorkflow,
  latestPolywrapWorkflowFormat,
} from ".";
import { DeserializeManifestOptions } from "../../";

import * as Semver from "semver";
import YAML from "js-yaml";

export function deserializePolywrapWorkflow(
  manifest: string,
  options?: DeserializeManifestOptions
): PolywrapWorkflow {
  let anyPolywrapWorkflow: AnyPolywrapWorkflow | undefined;
  try {
    anyPolywrapWorkflow = JSON.parse(manifest) as AnyPolywrapWorkflow;
  } catch (e) {
    anyPolywrapWorkflow = YAML.safeLoad(manifest) as
    | AnyPolywrapWorkflow
    | undefined;
  }

  if (!anyPolywrapWorkflow) {
    throw Error(`Unable to parse PolywrapWorkflow: ${manifest}`);
  }

  if (!options || !options.noValidate) {
    validatePolywrapWorkflow(anyPolywrapWorkflow, options?.extSchema);
  }

  anyPolywrapWorkflow.__type = "PolywrapWorkflow";

  const versionCompare = Semver.compare(
    Semver.coerce(anyPolywrapWorkflow.format) || anyPolywrapWorkflow.format,
    Semver.coerce(latestPolywrapWorkflowFormat) || latestPolywrapWorkflowFormat
  );

  if (versionCompare === -1) {
    // Upgrade
    return migratePolywrapWorkflow(anyPolywrapWorkflow, latestPolywrapWorkflowFormat);
  } else if (versionCompare === 1) {
    // Downgrade
    throw Error(
      `Cannot downgrade Polywrap version ${anyPolywrapWorkflow.format}, please upgrade your PolywrapClient package.`
    );
  } else {
    // Latest
    return anyPolywrapWorkflow as PolywrapWorkflow;
  }
}
