/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyPolywrapWorkflow,
  PolywrapWorkflow,
  PolywrapWorkflowFormats,
  latestPolywrapWorkflowFormat
} from ".";


type Migrator = {
  [key in PolywrapWorkflowFormats]?: (m: AnyPolywrapWorkflow) => PolywrapWorkflow;
};

export const migrators: Migrator = {
};

export function migratePolywrapWorkflow(
  manifest: AnyPolywrapWorkflow,
  to: PolywrapWorkflowFormats
): PolywrapWorkflow {
  let from = manifest.format as PolywrapWorkflowFormats;

  // HACK: Patch fix for backwards compatability
  if(from === "0.1" && ("0.1.0" in migrators)) {
    from = "0.1.0" as PolywrapWorkflowFormats;
  }

  if (from === latestPolywrapWorkflowFormat) {
    return manifest as PolywrapWorkflow;
  }

  if (!(Object.values(PolywrapWorkflowFormats).some(x => x === from))) {
    throw new Error(`Unrecognized PolywrapWorkflowFormat "${manifest.format}"`);
  }

  throw new Error(`This should never happen, PolywrapWorkflow migrators is empty. from: ${from}, to: ${to}`);
}
