/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyPolywrapWorkflow,
  PolywrapWorkflow,
  PolywrapWorkflowFormats,
  latestPolywrapWorkflowFormat
} from ".";
import { findShortestMigrationPath } from "../../migrations";
import { migrations } from "./migrations";

export function migratePolywrapWorkflow(
  manifest: AnyPolywrapWorkflow,
  to: PolywrapWorkflowFormats
): PolywrapWorkflow {
  let from = manifest.format as PolywrapWorkflowFormats;

  if (from === latestPolywrapWorkflowFormat) {
    return manifest as PolywrapWorkflow;
  }

  if (!(Object.values(PolywrapWorkflowFormats).some(x => x === from))) {
    throw new Error(`Unrecognized PolywrapWorkflowFormat "${manifest.format}"`);
  }

  const migrationPath = findShortestMigrationPath(migrations, from, to);
  if (!migrationPath) {
    throw new Error(
      `Migration path from PolywrapWorkflowFormat "${from}" to "${to}" is not available`
    );
  }

  let newManifest = manifest;

  for(const migration of migrationPath){
    newManifest = migration.migrateFn(newManifest) as AnyPolywrapWorkflow;
  }

  return newManifest as PolywrapWorkflow;
}
