/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyPolywrapManifest,
  PolywrapManifest,
  PolywrapManifestFormats,
} from ".";
import { findShortestMigrationPath } from "../../migrations";
import { migrators } from "./migrators";

export function migratePolywrapManifest(
  manifest: AnyPolywrapManifest,
  to: PolywrapManifestFormats
): PolywrapManifest {
  let from = manifest.format as PolywrapManifestFormats;

  if (!(Object.values(PolywrapManifestFormats).some(x => x === from))) {
    throw new Error(`Unrecognized PolywrapManifestFormat "${manifest.format}"`);
  }

  if (!(Object.values(PolywrapManifestFormats).some(x => x === to))) {
    throw new Error(`Unrecognized PolywrapManifestFormat "${to}"`);
  }

  const migrationPath = findShortestMigrationPath(migrators, from, to);
  if (!migrationPath) {
    throw new Error(
      `Migration path from PolywrapManifestFormat "${from}" to "${to}" is not available`
    );
  }

  let newManifest = manifest;

  for(const migrator of migrationPath){
    newManifest = migrator.migrate(newManifest) as AnyPolywrapManifest;
  }

  return newManifest as PolywrapManifest;
}
