/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  DappManifest as DappManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";

export {
  DappManifest0_0_1_prealpha_1,
};

export enum DappManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
}

export type AnyDappManifest =
  | DappManifest0_0_1_prealpha_1

export type DappManifest = DappManifest0_0_1_prealpha_1;

export const latestDappManifestFormat = DappManifestFormats["0.0.1-prealpha.1"]

export { migrateDappManifest } from "./migrate";

export { deserializeDappManifest } from "./deserialize";

export { validateDappManifest } from "./validate";
