/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyDappManifest,
  DappManifest,
  DappManifestFormats,
  latestDappManifestFormat
} from ".";


import { Tracer } from "@web3api/tracing-js";

type Migrator = {
  [key in DappManifestFormats]?: (m: AnyDappManifest) => DappManifest;
};

export const migrators: Migrator = {
};

export const migrateDappManifest = Tracer.traceFunc(
  "core: migrateDappManifest",
  (manifest: AnyDappManifest, to: DappManifestFormats): DappManifest => {
    const from = manifest.format as DappManifestFormats;

    if (from === latestDappManifestFormat) {
      return manifest as DappManifest;
    }

    if (!(from in DappManifestFormats)) {
      throw new Error(`Unrecognized DappManifestFormat "${manifest.format}"`);
    }

    throw new Error(`This should never happen, DappManifest migrators is empty. from: ${from}, to: ${to}`);
  }
);
