/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PluginManifest {
  /**
   * Polywrap manifest format version.
   */
  format: "0.3.0";
  /**
   * Basic project properties.
   */
  project: {
    /**
     * Name of this project.
     */
    name: string;
    /**
     * Type of this project.
     */
    type: string;
  };
  /**
   * Project source files.
   */
  source: {
    /**
     * Path to the project's entry point.
     */
    module: string;
    /**
     * Path to the project's graphql schema.
     */
    schema: string;
    /**
     * Redirects for the schema's imports.
     */
    import_redirects?: {
      /**
       * Import URI to be redirected.
       */
      uri: string;
      /**
       * Path to a graphql schema to be used for the import.
       */
      schema: string;
    }[];
  };
  /**
   * Project extension files (build, meta, deploy, infra).
   */
  extensions?: {
    /**
     * Path to the project build manifest file.
     */
    build?: string;
    /**
     * Path to project metadata manifest file.
     */
    meta?: string;
    /**
     * Path to project deploy manifest file.
     */
    deploy?: string;
    /**
     * Path to project infra manifest file.
     */
    infra?: string;
  };
  __type: "PluginManifest";
}
