/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  PluginManifest as PluginManifest_0_1
} from "./0.1";

export {
  PluginManifest_0_1,
};

export enum PluginManifestFormats {
  // NOTE: Patch fix for backwards compatability
  "v0.1.0" = "0.1.0",
  "v0.1" = "0.1",
}

export type AnyPluginManifest =
  | PluginManifest_0_1

export type PluginManifest = PluginManifest_0_1;

export const latestPluginManifestFormat = PluginManifestFormats["v0.1"]

export { migratePluginManifest } from "./migrate";

export { deserializePluginManifest } from "./deserialize";

export { validatePluginManifest } from "./validate";
