/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  PluginManifest as PluginManifest_0_1_0,
} from "./0.1.0";
import {
  PluginManifest as PluginManifest_0_2_0,
} from "./0.2.0";
import {
  PluginManifest as PluginManifest_0_3_0,
} from "./0.3.0";

export {
  PluginManifest_0_1_0,
  PluginManifest_0_2_0,
  PluginManifest_0_3_0,
};

export enum PluginManifestFormats {
  // NOTE: Patch fix for backwards compatability
  "v0.1" = "0.1",
  "v0.1.0" = "0.1.0",
  "v0.2.0" = "0.2.0",
  "v0.3.0" = "0.3.0",
}

export const PluginManifestSchemaFiles: Record<string, string> = {
  // NOTE: Patch fix for backwards compatability
  "0.1": "formats/polywrap.plugin/0.1.0.json",
  "0.1.0": "formats/polywrap.plugin/0.1.0.json",
  "0.2.0": "formats/polywrap.plugin/0.2.0.json",
  "0.3.0": "formats/polywrap.plugin/0.3.0.json",
}

export type AnyPluginManifest =
  | PluginManifest_0_1_0
  | PluginManifest_0_2_0
  | PluginManifest_0_3_0



export type PluginManifest = PluginManifest_0_3_0;

export const latestPluginManifestFormat = PluginManifestFormats["v0.3.0"]

export { migratePluginManifest } from "./migrate";

export { deserializePluginManifest } from "./deserialize";

export { validatePluginManifest } from "./validate";
