/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  PluginManifest as PluginManifest0_1_0
} from "./0.1.0";

export {
  PluginManifest0_1_0,
};

export enum PluginManifestFormats {
  "0.1.0" = "0.1.0",
}

export type AnyPluginManifest =
  | PluginManifest0_1_0

export type PluginManifest = PluginManifest0_1_0;

export const latestPluginManifestFormat = PluginManifestFormats["0.1.0"]

export { migratePluginManifest } from "./migrate";

export { deserializePluginManifest } from "./deserialize";

export { validatePluginManifest } from "./validate";
