/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyPluginManifest,
  PluginManifest,
  PluginManifestFormats,
  latestPluginManifestFormat
} from ".";
import { findShortestMigrationPath } from "../../migrations";
import { migrations } from "./migrations";

export function migratePluginManifest(
  manifest: AnyPluginManifest,
  to: PluginManifestFormats
): PluginManifest {
  let from = manifest.format as PluginManifestFormats;

  if (from === latestPluginManifestFormat) {
    return manifest as PluginManifest;
  }

  if (!(Object.values(PluginManifestFormats).some(x => x === from))) {
    throw new Error(`Unrecognized PluginManifestFormat "${manifest.format}"`);
  }

  const migrationPath = findShortestMigrationPath(migrations, from, to);
  if (!migrationPath) {
    throw new Error(
      `Migration path from PluginManifestFormat "${from}" to "${to}" is not available`
    );
  }

  let newManifest = manifest;

  for(const migration of migrationPath){
    newManifest = migration.migrateFn(newManifest) as AnyPluginManifest;
  }

  return newManifest as PluginManifest;
}
