/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  MetaManifest as MetaManifest0_0_1_prealpha_1
} from "./0.0.1-prealpha.1";
import {
  MetaManifest as MetaManifest0_0_1_prealpha_2
} from "./0.0.1-prealpha.2";
import {
  MetaManifest as MetaManifest0_0_1_prealpha_3
} from "./0.0.1-prealpha.3";

export {
  MetaManifest0_0_1_prealpha_1,
  MetaManifest0_0_1_prealpha_2,
  MetaManifest0_0_1_prealpha_3,
};

export enum MetaManifestFormats {
  "0.0.1-prealpha.1" = "0.0.1-prealpha.1",
  "0.0.1-prealpha.2" = "0.0.1-prealpha.2",
  "0.0.1-prealpha.3" = "0.0.1-prealpha.3",
}

export type AnyMetaManifest =
  | MetaManifest0_0_1_prealpha_1
  | MetaManifest0_0_1_prealpha_2
  | MetaManifest0_0_1_prealpha_3

export type MetaManifest = MetaManifest0_0_1_prealpha_3;

export const latestMetaManifestFormat = MetaManifestFormats["0.0.1-prealpha.3"]

export { migrateMetaManifest } from "./migrate";

export { deserializeMetaManifest } from "./deserialize";

export { validateMetaManifest } from "./validate";
