/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MetaManifest {
  format: "0.0.1-prealpha.1";
  name?: string;
  subtext?: string;
  description?: string;
  icon?: string;
  queries?: {
    name: string;
    query: string;
  }[];
}
