/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MetaManifest {
  format: "0.0.1-prealpha.2";
  name: string;
  subtext?: string;
  description?: string;
  repository?: string;
  icon?: string;
  links?: {
    name: string;
    icon?: string;
    url: string;
  }[];
  cookbook?: {
    constants?:
      | string
      | {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` ".*".
           */
          [k: string]: string;
        };
    menus?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` ".*".
       */
      [k: string]: string[];
    };
    recipes: Recipes;
  };
  __type: "MetaManifest";
}
export interface Recipes {
  /**
   * This interface was referenced by `Recipes`'s JSON-Schema definition
   * via the `patternProperty` ".*".
   */
  [k: string]:
    | {
        query: string;
        variables?: {
          [k: string]: unknown;
        };
      }[]
    | Recipes;
}
