/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CodegenManifest {
  /**
   * Polywrap codegen manifest format version.
   */
  format: "0.1.0" | "0.1";
  /**
   * Output directory for the generated code (default: ./src/wrap)
   */
  codegenDir?: string;
  /**
   * Output path for the built schema and manifest (default: ./build)
   */
  publishDir?: string;
  /**
   * Custom configuration for binding target.
   */
  config?: {
    [k: string]: unknown;
  };
  __type: "CodegenManifest";
}
