/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyCodegenManifest,
  CodegenManifest,
  CodegenManifestFormats,
  latestCodegenManifestFormat
} from ".";
import { findShortestMigrationPath } from "../../migrations";
import { migrators } from "./migrators";

export function migrateCodegenManifest(
  manifest: AnyCodegenManifest,
  to: CodegenManifestFormats
): CodegenManifest {
  let from = manifest.format as CodegenManifestFormats;

  if (from === latestCodegenManifestFormat) {
    return manifest as CodegenManifest;
  }

  if (!(Object.values(CodegenManifestFormats).some(x => x === from))) {
    throw new Error(`Unrecognized CodegenManifestFormat "${manifest.format}"`);
  }

  const migrationPath = findShortestMigrationPath(migrators, from, to);
  if (!migrationPath) {
    throw new Error(
      `Migration path from CodegenManifestFormat "${from}" to "${to}" is not available`
    );
  }

  let newManifest = manifest;

  for(const migrator of migrationPath){
    newManifest = migrator.migrate(newManifest) as AnyCodegenManifest;
  }

  return newManifest as CodegenManifest;
}
