/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WrapManifest {
  /**
   * Wrap manifest format version
   */
  version: "0.0.1";
  /**
   * Wrap language
   */
  type: string;
  /**
   * Wrapper name
   */
  name: string;
  /**
   * Type info of wrapper
   */
  abi: unknown;
  __type: "WrapManifest";
}
