/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  WrapManifest as WrapManifest0_0_1
} from "./0.0.1";

export {
  WrapManifest0_0_1,
};

export enum WrapManifestVersions {
  "0.0.1" = "0.0.1",
}

export type AnyWrapManifest =
  | WrapManifest0_0_1

export type WrapManifest = WrapManifest0_0_1;

export const latestWrapManifestVersion = WrapManifestVersions["0.0.1"]

export { migrateWrapManifest } from "./migrate";

export { deserializeWrapManifest } from "./deserialize";

export { validateWrapManifest } from "./validate";
