// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

import { PluginPackageManifest, Uri } from "@web3api/core-js";

export const manifest: PluginPackageManifest = {
  schema: `# TODO: should import and "implements" the api-resolver core-api schema
# https://github.com/Web3-API/monorepo/issues/75

type Query {
  tryResolveUri(
    authority: String!
    path: String!
  ): ApiResolver_MaybeUriOrManifest

  getFile(path: String!): Bytes
}

# TODO: should get replaced with an import
# https://github.com/Web3-API/monorepo/issues/75
type ApiResolver_MaybeUriOrManifest {
  uri: String
  manifest: String
}
`,
  implements: [new Uri("w3/api-resolver")],
};
