/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Manifest {
  description?: string;
  repository?: string;
  version: string;
  query?: ModuleSchema;
  mutation?: ModuleSchema;
  subgraph?: {
    file: string;
    id?: string;
  };
}
export interface ModuleSchema {
  schema?:
    | string
    | {
        file: string;
      };
  module?:
    | string
    | {
        file: string;
        language?: string;
      };
}
