/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Web3API {
  description?: string;
  repository?: string;
  version: string;
  query?: {
    [k: string]: unknown;
  };
  mutation?: {
    [k: string]: unknown;
  };
  subgraph?: {
    file: string;
    id?: string;
  };
  [k: string]: unknown;
}
