/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Manifest {
  description?: string;
  repository?: string;
  version: string;
  query?: {
    schema?:
      | string
      | {
          file: string;
        };
    module?:
      | string
      | {
          file: string;
          language?: string;
        };
  };
  mutation?: {
    schema?:
      | string
      | {
          file: string;
        };
    module?:
      | string
      | {
          file: string;
          language?: string;
        };
  };
  subgraph?: {
    file: string;
    id?: string;
  };
}
