/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BuildManifest {
  /**
   * Polywrap build manifest format version.
   */
  format: "0.0.1-prealpha.1";
  /**
   * Docker build artifact properties.
   */
  docker?: {
    /**
     * Docker image name.
     */
    name?: string;
    /**
     * Docker image file name.
     */
    dockerfile?: string;
    /**
     * Id of the docker image.
     */
    buildImageId?: string;
  };
  /**
   * Custom configuration.
   */
  config?: {
    [k: string]: unknown;
  };
  __type: "BuildManifest";
}
