/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AppManifest {
  /**
   * Polywrap app manifest format version.
   */
  format: "0.1.0";
  /**
   * Name of this wrapper package.
   */
  name: string;
  /**
   * Language in which the source code is written.
   */
  language: string;
  /**
   * Path to graphql schema.
   */
  schema: string;
  /**
   * Redirects for the manifest's imports.
   */
  import_redirects?: {
    /**
     * Import URI to be redirected.
     */
    uri: string;
    /**
     * Path to a WRAP Manifest to be used for the import.
     */
    info: string;
  }[];
  __type: "AppManifest";
}
