/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  AppManifest as AppManifest0_1_0
} from "./0.1.0";

export {
  AppManifest0_1_0,
};

export enum AppManifestFormats {
  "0.1.0" = "0.1.0",
}

export type AnyAppManifest =
  | AppManifest0_1_0

export type AppManifest = AppManifest0_1_0;

export const latestAppManifestFormat = AppManifestFormats["0.1.0"]

export { migrateAppManifest } from "./migrate";

export { deserializeAppManifest } from "./deserialize";

export { validateAppManifest } from "./validate";
