/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  AppManifest as AppManifest_0_1
} from "./0.1";

export {
  AppManifest_0_1,
};

export enum AppManifestFormats {
  "v0.1" = "0.1",
}

export type AnyAppManifest =
  | AppManifest_0_1

export type AppManifest = AppManifest_0_1;

export const latestAppManifestFormat = AppManifestFormats["v0.1"]

export { migrateAppManifest } from "./migrate";

export { deserializeAppManifest } from "./deserialize";

export { validateAppManifest } from "./validate";
