/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyAppManifest,
  AppManifest,
  AppManifestFormats,
  latestAppManifestFormat
} from ".";
import { findShortestMigrationPath } from "../../migrations";
import { migrations } from "./migrations";

export function migrateAppManifest(
  manifest: AnyAppManifest,
  to: AppManifestFormats
): AppManifest {
  let from = manifest.format as AppManifestFormats;

  if (from === latestAppManifestFormat) {
    return manifest as AppManifest;
  }

  if (!(Object.values(AppManifestFormats).some(x => x === from))) {
    throw new Error(`Unrecognized AppManifestFormat "${manifest.format}"`);
  }

  const migrationPath = findShortestMigrationPath(migrations, from, to);
  if (!migrationPath) {
    throw new Error(
      `Migration path from AppManifestFormat "${from}" to "${to}" is not available`
    );
  }

  let newManifest = manifest;

  for(const migration of migrationPath){
    newManifest = migration.migrateFn(newManifest) as AnyAppManifest;
  }

  return newManifest as AppManifest;
}
