/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyAppManifest,
  AppManifest,
  AppManifestFormats,
  latestAppManifestFormat
} from ".";

import {
  migrate as migrate_0_1_to_0_3_0
} from "./migrators/0.1_to_0.3.0";
import {
  migrate as migrate_0_2_to_0_3_0
} from "./migrators/0.2_to_0.3.0";

type Migrator = {
  [key in AppManifestFormats]?: (m: AnyAppManifest) => AppManifest;
};

export const migrators: Migrator = {
  "0.1": migrate_0_1_to_0_3_0,
  "0.2": migrate_0_2_to_0_3_0,
};

export function migrateAppManifest(
  manifest: AnyAppManifest,
  to: AppManifestFormats
): AppManifest {
  let from = manifest.format as AppManifestFormats;

  // HACK: Patch fix for backwards compatability
  if(from === "0.1.0" && ("0.1" in migrators)) {
    from = "0.1" as AppManifestFormats;
  }

  if (from === latestAppManifestFormat) {
    return manifest as AppManifest;
  }

  if (!(Object.values(AppManifestFormats).some(x => x === from))) {
    throw new Error(`Unrecognized AppManifestFormat "${manifest.format}"`);
  }

  const migrator = migrators[from];
  if (!migrator) {
    throw new Error(
      `Migrator from AppManifestFormat "${from}" to "${to}" is not available`
    );
  }

  return migrator(manifest);
}
