# generated by datamodel-codegen:
#   filename:  0.1.0.json
#   timestamp: 2022-09-21T13:12:40+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Extra, Field, constr


class Format(Enum):
    field_0_1_0 = '0.1.0'
    field_0_1 = '0.1'


class ImportRedirect(BaseModel):
    class Config:
        extra = Extra.forbid

    uri: str = Field(..., description='Source URI that needs to be redirected.')
    schema_: str = Field(
        ...,
        alias='schema',
        description='Path to GraphQL schema of the module to which URI will be redirected.',
    )


class Model(BaseModel):
    class Config:
        extra = Extra.forbid

    format: Format = Field(..., description='Polywrap plugin manifest format version.')
    name: constr(regex=r'^[a-zA-Z0-9\\-\\_]+$') = Field(..., description='Plugin name.')
    language: constr(regex=r'^plugin\\/[a-z0-9]+$') = Field(
        ..., description='Plugin language.'
    )
    module: Optional[
        constr(
            regex=r'^\\.?\\.?\\/?((\\/[\\w\\-\\.]+|\\/\\.\\.|\\/\\.)+\\/)?[\\w\\-\\.]+\\.?[\\w\\-\\.]*$'
        )
    ] = Field(None, description='Path to Polywrap implementation.')
    schema_: constr(
        regex=r'^\\.?\\.?\\/?((\\/[\\w\\-\\.]+|\\/\\.\\.|\\/\\.)+\\/)?[\\w\\-\\.]+\\.graphql$'
    ) = Field(..., alias='schema', description='Path to graphql schema.')
    import_redirects: Optional[List[ImportRedirect]] = Field(
        None, description='Redirects source URI to local wrapper or plugin.'
    )
