/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DocsManifest {
  /**
   * Polywrap Docs manifest format version.
   */
  format: "0.1.0";
  /**
   * The title of the docs.
   */
  title: string;
  /**
   * Path to the wrapper logo.
   */
  logo?: string;
  /**
   * Object containing sidebar pages where the object's keys are page slugs.
   */
  pages?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^([a-z\-])+$".
     */
    [k: string]: {
      /**
       * The title of the page.
       */
      title: string;
      /**
       * Path to the page
       */
      path: string;
    };
  };
  /**
   * The slug of the home page.
   */
  homePage?: string;
  /**
   * Object containing examples where the the object's keys are example slugs.
   */
  examples?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^([a-z\-])+$".
     */
    [k: string]: {
      /**
       * The title of the example.
       */
      title: string;
      /**
       * Wrap invocations as an array of example steps.
       */
      steps?: {
        /**
         * A description of the step rendered above the invocation code.
         */
        description?: string;
        /**
         * URI of the wrap being invoked.
         */
        uri: any;
        /**
         * Invoked method name.
         */
        method: string;
        /**
         * Invoked method arguments.
         */
        args?: {
          [k: string]: unknown;
        };
      }[];
    };
  };
  __type: "DocsManifest";
}
