/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DocsManifest {
  /**
   * Polywrap Docs manifest format version.
   */
  format: "0.1.0";
  /**
   * The title of the docs.
   */
  title: string;
  /**
   * Path to the wrapper logo.
   */
  logo?: string;
  /**
   * Sidebar pages. The first page is also the landing page.
   */
  pages?: {
    /**
     * The title of the page.
     */
    title: string;
    /**
     * Path to the page
     */
    path: string;
  }[];
  __type: "DocsManifest";
}
