/* eslint-disable @typescript-eslint/naming-convention */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DocsManifest {
  /**
   * Polywrap Docs manifest format version.
   */
  format: "0.1.0";
  /**
   * A description of the wrap.
   */
  description?: string;
  /**
   * Path to the wrap's logo.
   */
  logo?: string;
  /**
   * Website related to the wrap.
   */
  website?: string;
  /**
   * Url of the wrap's repository.
   */
  repository?: string;
  /**
   * Path to the readme page.
   */
  readme?: string;
  /**
   * Object containing examples where the the object's keys are example slugs.
   */
  examples?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^([a-z\-])+$".
     */
    [k: string]: {
      /**
       * The title of the example.
       */
      title: string;
      /**
       * Wrap invocations as an array of example steps.
       */
      steps?: {
        /**
         * A description of the step rendered above the invocation code.
         */
        description?: string;
        /**
         * URI of the wrap being invoked.
         */
        uri?: any;
        /**
         * Invoked method name.
         */
        method: string;
        /**
         * Invoked method arguments.
         */
        args?: {
          [k: string]: unknown;
        };
      }[];
    };
  };
  __type: "DocsManifest";
}
