/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  DocsManifest as DocsManifest_0_1_0,
} from "./0.1.0";

export {
  DocsManifest_0_1_0,
};

export enum DocsManifestFormats {
  // NOTE: Patch fix for backwards compatability
  "v0.1" = "0.1",
  "v0.1.0" = "0.1.0",
}

export const DocsManifestSchemaFiles: Record<string, string> = {
  // NOTE: Patch fix for backwards compatability
  "0.1": "formats/polywrap.docs/0.1.0.json",
  "0.1.0": "formats/polywrap.docs/0.1.0.json",
}

export type AnyDocsManifest =
  | DocsManifest_0_1_0


export type DocsManifest = DocsManifest_0_1_0;

export const latestDocsManifestFormat = DocsManifestFormats["v0.1.0"]

export { migrateDocsManifest } from "./migrate";

export { deserializeDocsManifest } from "./deserialize";

export { validateDocsManifest } from "./validate";
