/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  InfraManifest as InfraManifest0_1_0
} from "./0.1.0";

export {
  InfraManifest0_1_0,
};

export enum InfraManifestFormats {
  "0.1.0" = "0.1.0",
}

export type AnyInfraManifest =
  | InfraManifest0_1_0

export type InfraManifest = InfraManifest0_1_0;

export const latestInfraManifestFormat = InfraManifestFormats["0.1.0"]

export { migrateInfraManifest } from "./migrate";

export { deserializeInfraManifest } from "./deserialize";

export { validateInfraManifest } from "./validate";
