/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/index-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/index-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */

import {
  InfraManifest as InfraManifest_0_1_0,
} from "./0.1.0";

export {
  InfraManifest_0_1_0,
};

export enum InfraManifestFormats {
  // NOTE: Patch fix for backwards compatability
  "v0.1" = "0.1",
  "v0.1.0" = "0.1.0",
}

export const InfraManifestSchemaFiles: Record<string, string> = {
  // NOTE: Patch fix for backwards compatability
  "0.1": "formats/polywrap.infra/0.1.0.json",
  "0.1.0": "formats/polywrap.infra/0.1.0.json",
}

export type AnyInfraManifest =
  | InfraManifest_0_1_0


export type InfraManifest = InfraManifest_0_1_0;

export const latestInfraManifestFormat = InfraManifestFormats["v0.1.0"]

export { migrateInfraManifest } from "./migrate";

export { deserializeInfraManifest } from "./deserialize";

export { validateInfraManifest } from "./validate";
