/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyInfraManifest,
  InfraManifest,
  InfraManifestFormats,
  latestInfraManifestFormat
} from ".";

import {
  migrate as migrate_0_0_1_prealpha_1_to_0_0_1_prealpha_2
} from "./migrators/0.0.1-prealpha.1_to_0.0.1-prealpha.2";

type Migrator = {
  [key in InfraManifestFormats]?: (m: AnyInfraManifest) => InfraManifest;
};

export const migrators: Migrator = {
  "0.0.1-prealpha.1": migrate_0_0_1_prealpha_1_to_0_0_1_prealpha_2,
};

export function migrateInfraManifest(
  manifest: AnyInfraManifest,
  to: InfraManifestFormats
): InfraManifest {
  const from = manifest.format as InfraManifestFormats;

  if (from === latestInfraManifestFormat) {
    return manifest as InfraManifest;
  }

  if (!(from in InfraManifestFormats)) {
    throw new Error(`Unrecognized InfraManifestFormat "${manifest.format}"`);
  }

  const migrator = migrators[from];
  if (!migrator) {
    throw new Error(
      `Migrator from InfraManifestFormat "${from}" to "${to}" is not available`
    );
  }

  return migrator(manifest);
}
