/* eslint-disable */
/**
 * This file was automatically generated by scripts/manifest/migrate-ts.mustache.
 * DO NOT MODIFY IT BY HAND. Instead, modify scripts/manifest/migrate-ts.mustache,
 * and run node ./scripts/manifest/generateFormatTypes.js to regenerate this file.
 */
import {
  AnyInfraManifest,
  InfraManifest,
  InfraManifestFormats,
  latestInfraManifestFormat
} from ".";
import { findShortestMigrationPath } from "../../migrations";
import { migrations } from "./migrations";

export function migrateInfraManifest(
  manifest: AnyInfraManifest,
  to: InfraManifestFormats
): InfraManifest {
  let from = manifest.format as InfraManifestFormats;

  if (from === latestInfraManifestFormat) {
    return manifest as InfraManifest;
  }

  if (!(Object.values(InfraManifestFormats).some(x => x === from))) {
    throw new Error(`Unrecognized InfraManifestFormat "${manifest.format}"`);
  }

  const migrationPath = findShortestMigrationPath(migrations, from, to);
  if (!migrationPath) {
    throw new Error(
      `Migration path from InfraManifestFormat "${from}" to "${to}" is not available`
    );
  }

  let newManifest = manifest;

  for(const migration of migrationPath){
    newManifest = migration.migrateFn(newManifest) as AnyInfraManifest;
  }

  return newManifest as InfraManifest;
}
