const baseTypes = {
  u8: "u8",
  u16: "u16",
  u32: "u32",
  i8: "i8",
  i16: "i16",
  i32: "i32",
  string: "string",
  bool: "bool",
};

export type BaseTypes = typeof baseTypes;

export type BaseType = keyof BaseTypes;

export function isBaseType(type: string): type is BaseType {
  return type in baseTypes;
}

// based on:
// - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords
// - https://github.com/AssemblyScript/assemblyscript/blob/f54dbfb527842f3d68f18643bb614d104b4f0160/src/common.ts#L107
// - https://github.com/AssemblyScript/assemblyscript/blob/f54dbfb527842f3d68f18643bb614d104b4f0160/src/tokenizer.ts#L181
export const reservedWordsAS: Set<string> = new Set([
  "async",
  "await",
  "arguments",
  "abstract",
  "as",
  "break",
  "const",
  "class",
  "catch",
  "case",
  "continue",
  "constructor",
  "default",
  "declare",
  "do",
  "delete",
  "debugger",
  "else",
  "enum",
  "export",
  "extends",
  "for",
  "from",
  "function",
  "finally",
  "get",
  "if",
  "in",
  "is",
  "implements",
  "import",
  "instanceof",
  "interface",
  "keyof",
  "let",
  "module",
  "new",
  "namespace",
  "of",
  "private",
  "package",
  "public",
  "protected",
  "return",
  "readonly",
  "switch",
  "static",
  "set",
  "super",
  "this",
  "type",
  "try",
  "throw",
  "typeof",
  "var",
  "while",
  "with",
  "yield",
  // types
  "i8",
  "i16",
  "i32",
  "i64",
  "isize",
  "u8",
  "u16",
  "u32",
  "u64",
  "usize",
  "bool",
  "f32",
  "f64",
  "v128",
  "funcref",
  "externref",
  "anyref",
  "eqref",
  "i31ref",
  "dataref",
  "i8x16",
  "u8x16",
  "i16x8",
  "u16x8",
  "i32x4",
  "u32x4",
  "i64x2",
  "u64x2",
  "f32x4",
  "f64x2",
  "void",
  "number",
  "boolean",
  "string",
  "native",
  "indexof",
  "valueof",
  "returnof",
  "nonnull",
  // aliases
  "null",
  "true",
  "false",
  // constants
  "ASC_TARGET",
  "ASC_RUNTIME",
  "ASC_NO_ASSERT",
  "ASC_MEMORY_BASE",
  "ASC_TABLE_BASE",
  "ASC_OPTIMIZE_LEVEL",
  "ASC_SHRINK_LEVEL",
  "ASC_LOW_MEMORY_LIMIT",
  "ASC_EXPORT_RUNTIME",
  "ASC_WASI",
  "ASC_FEATURE_SIGN_EXTENSION",
  "ASC_FEATURE_MUTABLE_GLOBALS",
  "ASC_FEATURE_NONTRAPPING_F2I",
  "ASC_FEATURE_BULK_MEMORY",
  "ASC_FEATURE_SIMD",
  "ASC_FEATURE_THREADS",
  "ASC_FEATURE_EXCEPTION_HANDLING",
  "ASC_FEATURE_TAIL_CALLS",
  "ASC_FEATURE_REFERENCE_TYPES",
  "ASC_FEATURE_MULTI_VALUE",
  "ASC_FEATURE_GC",
  "ASC_FEATURE_MEMORY64",
  "ASC_VERSION_MAJOR",
  "ASC_VERSION_MINOR",
  "ASC_VERSION_PATCH",
  // classes
  "I8",
  "I16",
  "I32",
  "I64",
  "Isize",
  "U8",
  "U16",
  "U32",
  "U64",
  "Usize",
  "Bool",
  "F32",
  "F64",
  "V128",
  "Funcref",
  "Externref",
  "Anyref",
  "Eqref",
  "I31ref",
  "Dataref",
  "String",
  "Object",
  "Array",
  "StaticArray",
  "Set",
  "Map",
  "Function",
  "ArrayBufferView",
  "ArrayBuffer",
  "Math",
  "Mathf",
  "NativeMath",
  "NativeMathf",
  "Int8Array",
  "Int16Array",
  "Int32Array",
  "Int64Array",
  "Uint8Array",
  "Uint8ClampedArray",
  "Uint16Array",
  "Uint32Array",
  "Uint64Array",
  "Float32Array",
  "Float64Array",
  "TemplateStringsArray",
  "Error",
  // runtime
  "abort",
  "trace",
  "seed",
  "pow",
  "ipow32",
  "ipow64",
  "mod",
  "__alloc",
  "__realloc",
  "__free",
  "__new",
  "__renew",
  "__link",
  "__collect",
  "__typeinfo",
  "__instanceof",
  "__visit",
  "__newBuffer",
  "__newArray",
]);
